server:
  port: 8085
  servlet:
    context-path: /saving-account

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: [USERNAME]
    password: [PASSWORD]
  main:
    allow-bean-definition-overriding: true
