server:
  port: 8085
  servlet:
    context-path: /saving-account-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: liviutzubiur28
  main:
    allow-bean-definition-overriding: true
